cookie:
  expiry_days: 30
  key: abcdefghijklmnopqrstuvwxyz1234567890
  name: medismart_auth_cookie
credentials:
  usernames:
    admin:
      email: admin@hospital.com
      first_name: System
      last_name: Administrator
      password: $2b$12$.kg15QCWMYANm8QeFivSFOJ2W8v18eO0VStuGbn0PQvKJIZ4SG2kW
      roles:
      - doctor
